services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - three-tier
    depends_on:
      - backend


  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_PORT: 3306
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: contacts_db
    networks:
      - three-tier
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: contacts_db
    ports:
      - "3306:3306"
    networks:
      - three-tier
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  three-tier:
    driver: bridge

volumes:
  mysql_data: