apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: "mysql-service"  
  DB_PORT: "3306"
  DB_USER: "root"    
  DB_PASSWORD: "rootpass"  
  DB_NAME: "contacts_db"    
  NODE_ENV: "production"     