apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cm9vdHBhc3M=    # "rootpass" in base64
  user: cm9vdA==                 # "root" in base64
  password: cm9vdHBhc3M=         # "rootpass" in base64